dist: trusty
sudo: required

language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - cppcheck

before_script:
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake .
  - make

script:
  - valgrind --track-origins=yes --leak-check=full ./testing
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./project
  - ./linters/run.sh --local